language: cpp
compiler: gcc

os: linux
addons:
  apt:
    packages:
      - gcc-7

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - cmake CMakeLists.txt
  - cmake  --build . --target neat
