language: cpp
compiler: gcc
dist: bionic

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - valgrind
      - cmake

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - make
  - ctest -VV
